tokio-rs/tracing-opentelemetry

.config/nextest.toml, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/CI.yml, .github/workflows/audit.yml, .github/workflows/release.yml
These are mostly copied over from `tokio-rs/tracing`, with
modifications (removing builds for other crates, etc).
=> chore: add CI, Codeowners, and issue/PR templates

Cargo.toml, examples/opentelemetry-remote-context.rs, examples/opentelemetry.rs
As part of moving tracing-opentelemetry over, I'm moving the tracing-opentelemetry examples over from `tokio-rs/tracing` to here.
=> chore: migrate examples from the main tracing repo over

Cargo.toml
Changes the URL for the repository in Cargo.toml
Clicking "repository" in crates.io leads to the old parent repository
Change the URL
=> Update the repository URL in Cargo.toml

Cargo.toml
Because opentelemetry tracer was moved to own repository, homepage and repository parameters of Cargo.toml should represent the change.
=> Update homepage and repository links

Cargo.toml, README.md, examples/opentelemetry.rs, src/layer.rs, src/lib.rs, src/metrics.rs, src/tracer.rs, tests/metrics_publishing.rs, tests/trace_state_propagation.rs
I noticed that this repo got the cut-off before opentelemetry 0.18 was committed into the main repo so I tried to backport what was there.
This is pretty much a backport from the code that @jtescher did on the main repo.
Let me know if you see something wrong, I tried to adapt the rejections the best way possible.
This fix #8
=> fix: Backport opentelemetry 0.18 code from main repo

CHANGELOG.md, Cargo.toml, README.md, src/layer.rs, src/lib.rs
Backport other release changes from https://github.com/tokio-rs/tracing/pull/2312
=> Backport v0.18 otel release changes

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Changelog:
- Upgrade to `v0.19.0` of `opentelemetry` (#12)
For list of breaking changes in OpenTelemetry, see the [v0.19.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0190).
- Update MSRV to require rust v1.60+, as `opentelemetry` requires it now (#12)
Thanks to @jaysonsantos, @briankung, and @humb1t for contributing to this release!
=> Prepare for v0.19.0 release

src/span_ext.rs
Closes #25
When I tried to find a parent span as someone not familiar with the code I tried using what's in the builder and if there's None I tried the parent context (which always has trace ID, it just might be invalid).
This change should simplify this for people unfamiliar with the codebase by getting rid of the trace ID that's not used.
Set trace ID in builder to `None`. It has not been used anywhere if parent_cx contained a valid trace ID so no other changes are needed.
=> Set builder parent span to None when manually setting parent

Cargo.toml, benches/trace.rs
In order to more easily interpret benchmark data, I enabled criterion HTML reports and flame graphs.
=> Enable flame graphs and reports for benchmarks

src/span_ext.rs
This PR:
* Adds a function `set_attribute` to `OpenTelemetrySpanExt` to allow setting attributes directly on the OpenTelemetry `SpanBuilder`.
This allows users to set more than the tracing maximum of 32 fields.
There was a workaround I came up with without using the function involving wrapping the `Registry` in an Arc and accessing `OtelData` directly, but that led to [this bug in tracing-subscriber](https://github.com/tokio-rs/tracing/issues/2668).
=> Add set_attribute function

Cargo.toml, src/layer.rs, src/lib.rs, src/metrics.rs, src/tracer.rs, tests/metrics_publishing.rs
Update opentelemetry  dependency to use the latest opentelemetry from the tracing ecosystem.
Modified code affected by opentelemetry changes
=> update opentelemetry to 0.20.0

CHANGELOG.md, Cargo.toml
Changelog:
- Add `OpenTelemetrySpanExt::set_attribute` function (#34)
- Upgrade to `v0.20.0` of `opentelemetry` (#36)
For list of breaking changes in OpenTelemetry, see the
[v0.20.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/v0.20.0/opentelemetry-api/CHANGELOG.md#v0200).
=> Prepare for v0.20.0 release

Cargo.toml, benches/metrics.rs, src/metrics.rs, tests/metrics_publishing.rs
Support https://github.com/tokio-rs/tracing-opentelemetry/issues/32
This change will allow user to associate Attributes with metrics from tracing.
1. MetricsLayer is only interested in events that contain fields with metrics prefixes such as `counter`, so I have utilized the [tracing_subscriber Filter trait](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/layer/#per-layer-filtering).
2. Since it's necessary to pass Attributes when outputting Measurements, it's required to complete the visit for all fields first before invoking the Metrics API(`Counter:add()`).
`SmallVec` is used to hold Attribute KeyValues, Metrics names, and Instruments for invocation, aiming to avoid allocations in typical use cases.
=> feat: produce measurement with attributes

Cargo.toml, README.md, examples/opentelemetry-remote-context.rs, src/lib.rs, src/metrics.rs, src/span_ext.rs, src/tracer.rs, tests/metrics_publishing.rs, tests/trace_state_propagation.rs
`opentelemetry` is going to be deprecated in favor of separated crates.
Use the `opentelemetry_sdk` crate for SDK calls instead of `opentelemetry::sdk`
=> Move off of opentelemetry in favor of separate crates.

src/layer.rs, src/lib.rs
* Update semantic-conventions repository link to newly created one.
* Update the renamed attribute used in the example
* `http.url` -> `url.full` 
* [CHANGELOG](https://github.com/open-telemetry/semantic-conventions/blob/3bd1c39e5f6aae7ea942c50bd771fa2e7e408249/CHANGELOG.md?plain=1#L106)
=> docs: update semantic-conventions link

Cargo.toml, examples/opentelemetry-otlp.rs
* Provide specific example of how to set up various opentelemetry configrations  from tracing When connecting tracing and opentelemetry ecosystems
This example aims to demonstrate the following points
* tracing-opentelemetry configuration is done through the open telemetry sdk
* telemetry export is done using a plugin (opentelemetry-otlp), and the plugin provides the sdk construct helper methods
=> chore: add opentelemetry-otlp integration example

src/span_ext.rs, tests/trace_state_propagation.rs
Fix following issues
* https://github.com/tokio-rs/tracing-opentelemetry/issues/54
* https://github.com/tokio-rs/tracing-opentelemetry/issues/45
* Revert https://github.com/tokio-rs/tracing-opentelemetry/pull/26/files
* When an invalid(empty) Context is extracted from the propagator and passed to OpenTelemetrySpanExt::set_parent(), if none is set for trace_id, root and child trace id will not match
* I can confirm that this change works in [reproduction](https://github.com/notheotherben/tracing-opentelemetry-traceid-repro) that @notheotherben created
* add regression test case which propagate empty context
=> fix: trace id did not match when propagating invalid context

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Changelog:
- Ability to produce measurement with attributes (#43)
- `MetricsLayer` is now generic over the its `Subscriber` impl to support [per-layer filtering] (#43)
- Trace IDs not matching when propagating invalid contexts (#55)
[per-layer filtering]: https://docs.rs/tracing-subscriber/0.3.17/tracing_subscriber/layer/index.html#per-layer-filtering
=> Prepare for v0.21.0 release

README.md
The `Cargo.toml` is missing the `opentelemetry_sdk` dependency to get the `Basic Usage` example working.
Ensure new users to tracing-otel can get up and running easily with the provided example.
Update the `Cargo.toml` to the correct set of deps used in the README example.
=> Update README example Cargo.toml

src/layer.rs
Some `Debug` implementations access a span's extensions, for example a `color_eyre` `Report` when printing a Spantrace.
This can currently lead to a deadlock because `tracing-opentelemetry`'s tracing `Layer` holds an `extensions_mut()` guard for its Span while recording the event.
Move the the `OtelData` out of the span to not hold the lock and later write the extension back.
=> Fix potential deadlock

examples/opentelemetry-error.rs, src/layer.rs, tests/errors.rs
Currently, the tracing instrumentation macro emits a single event after the function call, but in the current span, with just a field named error set.
For example:
```rust
#[instrument(err)]
fn test() -> Result<(), ()> {
...body
}
```
gets roughly expanded to 
```rust
fn test() -> Result<(), ()> {
let span = span!("test")
fn inner() -> Result<(), ()> {
...body
}
match inner() {
Ok(x) => Ok(x),
Err(err) => {
error!(error=%err)
Err(err)
}
}
```
In the error case of the result, the macro will emit an error level event with just an `error` field set to the display (or debug) value of the returned error. 
While there exists support for the Error primitive in tracing, the primitive only supports 'static Errors. See https://github.com/tokio-rs/tracing/issues/1308
This PR adds support to use this …
=> Add support for instrumented functions which return Result

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Changelog:
- Upgrade to `v0.21.0` of `opentelemetry` For list of breaking changes in OpenTelemetry, see the [v0.21.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/v0.21.0/opentelemetry/CHANGELOG.md).
- Update MSRV to require Rust 1.65+, as `opentelemetry` requires it now. (#68)
- WASM Support (#57)
- Fix potential deadlock (#59)
=> Prepare for v0.22.0 release

src/metrics.rs, tests/metrics_publishing.rs
Closes #81
Adds metrics attributes given as Display or Debug
As described in #81, currently the metrics layer doesn't do anything when Debug / Display values are given like so:
```rust
tracing::info!(
counter.myapp.organization = 1,
%organization.status,
?organization.type
);
```
This implements `MetricsVisitor::record_debug` so that it can export them as metrics attributes.
Push the given argument to the `self.attributes` in `MetricsVisitor::record_debug` where it does nothing currently like it does for str value:
https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/src/metrics.rs#L148-L150
```rust
fn record_debug(&mut self, _field: &Field, _value: &dyn fmt::Debug) {
// Do nothing
}
```
https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/src/metrics.rs#L208-L211 …
=> Display attribute in metrics

src/layer.rs, tests/parents.rs
Currently, when an event is created, no matter what is set as its parent, `OpenTelemetryLayer` will call `lookup_current` and use that as the parent span. It should honor the configured parent, if any, or be ignored, if the parent is explicitly set to `None`.
The code is changed so that the parent is correctly resolved. The logic is somewhat similar to `OpenTelemetryLayer::parent_context`.
=> Honor explicit parent spans for events

Cargo.toml, benches/trace.rs, src/layer.rs, tests/parallel.rs, tests/parents.rs
#94 - Mutli-threaded tracing drops most of the events
I have reorganized the code so that the lock on extensions is held, but not while `record` is called which should solve the deadlock originally solved in #59 
I've used the benchmark from #93, please ignore the "filtered" vs "non_filtered" distinction, for the purpose of this PR they should be identical cases.
See results in later comment as the code got changed.
=> fix: process parallel events and potential deadlock in `on_record`

src/metrics.rs, tests/metrics_publishing.rs
rust-opentelemetry has dropped this, as it is
recommended against by the otel spec.
=> remove i64_histogram support

README.md
Closes #126 
The example in readme was broken because it has been renamed.
Changed the name of example to be run. I've also cleared up ports in the jaeger.
The example now outputs much less information than the example before, but that more compilcated example started using stdout instead.
=> Fix example usage in readme

Cargo.toml, examples/opentelemetry-error.rs, src/layer.rs, src/span_ext.rs
Bump otel related crates to the latest version.
This PR will close the following PRs:
- https://github.com/tokio-rs/tracing-opentelemetry/pull/132
- https://github.com/tokio-rs/tracing-opentelemetry/pull/133
- https://github.com/tokio-rs/tracing-opentelemetry/pull/134
- https://github.com/tokio-rs/tracing-opentelemetry/pull/135
- https://github.com/tokio-rs/tracing-opentelemetry/pull/136
- https://github.com/tokio-rs/tracing-opentelemetry/pull/137
Also
- https://github.com/tokio-rs/tracing-opentelemetry/pull/139
- https://github.com/tokio-rs/tracing-opentelemetry/issues/141
Bump version in crates and alter some API usage.
=> deps: Bump to otel to version 0.23

Cargo.toml
Use 2021 edition instead to make it a bit new.
As titled.
=> chore: Use 2021 edition instead

benches/trace.rs, src/layer.rs
Closes #116 
Currently, the open telemetry span is considered to be running until the tracing span is dropped and closed. This can be an issue in cases where either the span is held onto in case the operation needs more processing which was not known beforehand or when a structure holds onto the span.
This is an issue especially if an instrumented task is spawned as `tracing` will hold onto all its ancestors. Therefore until the spawned task ends, the parent span will also be considered not closed.
The time is set every time a span is exited. This incurs a lookup in extensions during `on_exit`.
It might also make sense to do it during the first `on_enter` call. I can't think of a scenario where someone creates spans beforehand and enters them only significantly later though (maybe that …
=> fix: set span end time when it exits

.github/workflows/CI.yml, src/layer.rs, src/lib.rs
I was attempting to use this library with a WASI target and it was not compiling. The cfg options in the Cargo.toml and the source files did not match. See #146.
Fix cfg options to match.
=> WASI support

src/span_ext.rs, tests/trace_state_propagation.rs
Fixes https://github.com/tokio-rs/tracing-opentelemetry/issues/150
Test fails without changes and passes with.
=> Invalidate sample decision on set parent fix #150

.github/workflows/CI.yml, Cargo.toml, benches/trace.rs, examples/opentelemetry-error.rs, examples/opentelemetry-otlp.rs, src/layer.rs, src/tracer.rs, tests/metrics_publishing.rs, tests/parallel.rs
=> Upgrade to opentelemetry 0.24

CHANGELOG.md, Cargo.toml, examples/opentelemetry-otlp.rs, src/layer.rs, src/lib.rs, tests/metrics_publishing.rs
Update opentelemetry depencencies to 0.25
https://github.com/open-telemetry/opentelemetry-rust/releases/tag/opentelemetry-0.25.0
From version 0.25, OpenTelemetry started using a unified version across all crates.
https://github.com/open-telemetry/opentelemetry-rust/issues/2084
* Upgrade opentelemetry deps to 0.25
* Remove `AttributeSet` from tests
* https://github.com/open-telemetry/opentelemetry-rust/pull/2045
* Rename deprecated `deployment.environment` semantic conv to `deployment.environment.name`
* https://opentelemetry.io/docs/specs/semconv/attributes-registry/enduser/
=> Upgrade to opentelemetry 0.25

CHANGELOG.md, Cargo.toml, examples/opentelemetry-otlp.rs, src/layer.rs, tests/metrics_publishing.rs
Update opentelemetry depencencies to 0.26
https://github.com/open-telemetry/opentelemetry-rust/releases/tag/opentelemetry-0.26.0
* Upgrade opentelemetry deps to 0.26
* Adapt to the API changes of OpenTelemetry's `Key`
* https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#changelog
* Adapt to the removal of the `AggregationSelector` trait and `DefaultAggregationSelector` struct in `opentelemetry-sdk`.
* https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/CHANGELOG.md#v0260
=> Upgrade to opentelemetry 0.26

README.md, examples/basic.rs
=> Update README with versioning notes

src/layer.rs
In the implementation of the `on_close` method, only hold the lock on span's extension to retrieve the extension data, but release it before processing and exporting.
To achieve optimal performance, span locks should be held for as little time as possible.
It's especially troublesome to hold the lock while arbitrary code in the generic OpenTelemetry span and exporter is called to export the span.
Reduce the locked code section to what's needed to remove the data of interest from the extension map.
=> Reduce locking in the implementation of `Layer::on_close`

src/span_ext.rs, tests/span_ext.rs
I have found that when working with `tracing` spans created by 3rd party libraries, it is incredibly difficult to set the OpenTelemetry Status of the span, which results in always having an unset span in my visualization tool.
In this case, I am working with the span created by the `aws_lambda_runtime` [crate](https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/lambda-runtime/src/layers/otel.rs#L75).
Unfortunately, since the span in the `aws_lambda_runtime` crate does not include the `otel.status_code` attribute upfront the `OpenTelemetryLayer::SpanAttributeVisitor::record_str` and `OpenTelemetryLayer::SpanAttributeVisitor::record_debug`  never gets triggered when calling `tracing::Span::current().record("otel.status_code", "ok");` This behavior of the `record` function ignoring …
=> adding support for setting the status of the span through SpanExt

src/layer.rs
See #180 for a description.
This PR implements the `OpenTelemetryLayer::with_level` setting, to disable (enabled by default) attaching the level tag to exported spans.
There are several concerns I see before recommending merging this:
* Will enable by default break code which manually set the `level` field? If so, disable-by-default seems smarter.
* Event levels are still always exported, should we also restrict this?
* I am somewhat confused, but it seems error level *events* set the *span* status to error. Is this behaviour intuitive, once we have a level attached to the span? Should error spans always set the span status?
=> Add level metadata to spans

.github/workflows/CI.yml, Cargo.toml, benches/metrics.rs, examples/opentelemetry-error.rs, examples/opentelemetry-otlp.rs, src/layer.rs, src/metrics.rs, tests/metrics_publishing.rs
New version 0.27.0 of the opentelemetry crates was recently released.
I've updated the dependencies and fixed any outstanding compilation issues caused by breaking changes in the upstream.
Two caveats:
* I was not able to resolve the compilation issues with https://github.com/tokio-rs/tracing-opentelemetry/blob/95f9ab97e239e5789d71b9636445d89e47612f65/benches/metrics.rs since the `NoopMeterProvider` has been hidden: https://github.com/open-telemetry/opentelemetry-rust/pull/2191
* The metric "views" are now gated behind the feature `spec_unstable_metrics_views`, and I wasn't sure whether to still include it in the example: https://github.com/MathiasPius/tracing-opentelemetry/blob/d18214596c97b1243ee955a63bed3875a4f8f5f9/examples/opentelemetry-otlp.rs#L47-L82
=> chore: update opentelemetry dependencies to 0.27.0

examples/opentelemetry-otlp.rs, tests/batch_global_subscriber.rs
Fixes #159
Use of `global::shutdown_tracer_provider` has regressed since opentelemetry 0.23.
Change the opentelemtry-otlp example to call `shutdown` on the `TracingProvider` available in scope.
Also added an integration test to verify the export behavior is as expected.
=> Fix the example installing `OpenTelemetryLayer` into a global subscriber

src/layer.rs
When using the tracing macros and trying to explicitly set the 'name' of the event, for example:
```rust
event!(name: "test", Level::INFO, field1 = "field1");
```
This event will get emitted to open telemetry as an event with an empty name. The 'name' information will be completely lost. It seems common for this information to get dropped actually, see: https://github.com/tokio-rs/tracing/issues/2774
In on_event I set the event name to `event.metadata().name()` which should be the name of the event that is handed down from tracing. I am unfamiliar with this code and the wider tracing/opentelemtry ecosystem so I am not sure this is a good way to solve this issue, or if this is even a real issue. I am also not sure what this change would break, and what kind of backward compatibility …
=> use the tracing event name as the otel event name

src/layer.rs
The documentation doesn't provide the default value of tracked_inactivity for `OpenTelemetryLayer` .
Specify that, by default, inactivity tracking is enabled.
=> doc: tracked inactivity default

CHANGELOG.md, Cargo.toml, examples/opentelemetry-error.rs, tests/batch_global_subscriber.rs, tests/errors.rs, tests/filtered.rs, tests/follows_from.rs, tests/parallel.rs, tests/parents.rs, tests/span_ext.rs, tests/trace_state_propagation.rs
This PR updates the dependencies from opentelemetry 0.28.0 to 0.29.0. The update requires adapting to breaking changes in the `SpanExporter` trait interface, which now requires immutable references (`&self` instead of `&mut self`) and uses `async fn` syntax rather than returning `BoxFuture`.
- Updated opentelemetry dependencies from 0.28.0 to 0.29.0 in Cargo.toml
- Updated all `SpanExporter` trait implementations in test files and examples to match the breaking changes in the 0.29.0 release:
- Changed `&mut self` to `&self` in method signatures
- Changed return type from `BoxFuture<'static, OTelSdkResult>` to using `async fn` that returns `OTelSdkResult` directly
- Removed unnecessary `BoxFuture` imports
- Updated CHANGELOG.md with the breaking change
The specific breaking changes in …
=> chore: update from opentelemetry-sdk 0.28.0 to 0.29.0

CHANGELOG.md, README.md, src/lib.rs, src/span_ext.rs, tests/metrics_publishing.rs, tests/span_ext.rs
This PR adds methods to `OpenTelemetrySpanExt` for directly adding OpenTelemetry span events, addressing the limitations of using `tracing::event!` for events with dynamic attributes.
Fixes #200
As discussed in issue #200, the current `tracing::event!` macro requires attribute keys to be known at compile time. This makes it difficult or impossible to record OpenTelemetry span events with dynamic attributes (e.g., from processing arbitrary JSON payloads) without resorting to lossy serialization, which hinders observability.
This change provides a way to directly add `opentelemetry::trace::Event` objects with dynamic `Vec<KeyValue>` attributes, similar to how `set_attribute` allows setting dynamic span attributes. This improves flexibility, makes porting code easier, and aligns better with …
=> feat: Add OpenTelemetrySpanExt methods for direct span event creation

examples/opentelemetry-otlp.rs
Logs to Jaeger will use the service name "unknown_service" instead of the crate name as intended.
See #199 for details.
Using `with_service_name` instead of declaring it in the Registry.
=> OTLP Example logging with incorrect ‘service.name’

CHANGELOG.md, Cargo.toml, tests/metrics_publishing.rs
Hi, I upgraded to the newest opentelemetry 0.30 and it broke compatibility with this crate. This should hopefully fix those incompatibility issues.
There were some breaking changes with the upgrade to otel 0.30: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/CHANGELOG.md#0300
I was able to fix upgrade them without much of an issue. The only compilation issues were in the metrics_publishing test. A few of the types used in that test now require the `experimental_metrics_custom_reader` feature to be enabled in the opentelemetry-sdk package.
Bump the versions & fix the one test file that had compilation errors.
Please let me know if I'm missing anything. Thanks!
=> Upgrade to otel 0.30
